const BlogPosts = [
  {
    id: 1,
    Image: "../asset/img/blog-1 (2).jpg",
    title: "top 6 evil eye earings that will rock your world",
    comments: 3,
    data: "Nov 12, 2022",
    admin: "admin",
    product: "Fine Watches , handbags",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium mollis ex, vel interdum",
  },
  {
    id: 2,
    Image: "../asset/img/blog-2 (2).jpg",
    title: "Top 10 Bags Adding Colour To Your Wardrobe",
    comments: 0,
    data: "Nov 14, 2022",
    admin: "admin",
    product: "Bracelets, handbags",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium mollis ex, vel interdum",
  },

  {
    id: 4,
    Image: "../asset/img/blog-3 (2).jpg",
    title: "Top 5 Watches Adding To Your Collection",
    comments: 1,
    data: "Nov 17, 2022",
    admin: "admin",
    product: "Fine Watches",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium mollis ex, vel interdum",
  },
  {
    id: 4,
    Image: "../asset/img/blog-9.jpg",
    title: "Is it Better to Buy Limited Edition of glasses?",
    comments: 0,
    data: "Nov 12, 2022",
    admin: "admin",
    product: "Fine glasses",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium mollis ex, vel interdum",
  },
  {
    id: 5,
    Image: "../asset/img/blog-7.jpg",
    title: "11 Messenger Bags for School That Make the Grade",
    comments: 0,
    data: "Oct 10, 2022",
    admin: "admin",
    product: "Fine Watches,Handbags",
  },
  {
    id: 6,
    Image: "../asset/img/blog-4.jpg",
    title: "Guide to Engagement Ring Styles",
    comments: 4,
    data: "Nov 7, 2022",
    admin: "admin",
    product: "Earrings,Rings",
  },
  {
    id: 7,
    Image: "../asset/img/blog-11.jpg",
    title: "Tips and Tricks to Wear Bracelets with Different Outfits",
    comments: 2,
    data: "Nov 14, 2022",
    admin: "admin",
    product: "Necklaces,Rings",
  },
  {
    id: 8,
    Image: "../asset/img/blog-5..jpg",
    title: "Pantone Color of the Year Living Coral Wedding Inspiration",
    comments: 5,
    data: "Nov 7, 2022",
    admin: "admin",
    product: "Earrings , Necklaces",
  },
  {
    id: 9,
    Image: "../asset/img/blog-10.jpg",
    title: "15 Jewellery Style Tips You Need to Know",
    comments: 0,
    data: "Nov 7, 2022",
    admin: "admin",
    product: "Charms , Necklaces",
  },
  {
    id: 10,
    Image: "../asset/img/blog-6-1.jpg",
    title: "14 Impressive It Bags That Have Made Fashion History",
    comments: 0,
    data: "Nov 5, 2022",
    admin: "admin",
    product: "Earrings , Handbags",
  },
  {
    id: 11,
    Image: "../asset/img/blog-8.jpg",
    title: "60 Ideas for Items to Use in Custom Wood earrings",
    comments: 2,
    data: "oCt 25, 2022",
    admin: "admin",
    product: "Earrings , Rings",
  },
  {
    id: 12,
    Image: "../asset/img/blog-15.jpg",
    title: "5 tips for choosing the perfect necklace length",
    comments: 0,
    data: "OCt 2, 2022",
    admin: "admin",
    product: "Earrings",
  },
];

export default BlogPosts;
