const shopitems = [
  {
    id: "1",
    name: "Gold-Plated Pearl Drop Earrings",
    iamge: "../asset/img/new-1.jpg",
    price: 133.5,
    hot: "Hot",
    category: "Earrings",
  },
  {
    id: "2",
    name: "Pearl Drop Stud Set of Two",
    iamge: "../asset/img/new-2.jpg",
    price: 139.5,
    hot: "-50%",
    category: "Earrings",
  },
  {
    id: " 3",
    name: "Double Wave Hoop Earings",
    iamge: "../asset/img/new-3.jpg",
    price: 53.75,
    hot: "Hot",
    category: "Earrings",
  },
  {
    id: "4",
    name: "Circle Charm Necklace with Diamonds",
    iamge: "../asset/img/new-4.jpg",

    price: 49.99,
    hot: "-24%",
    category: "necklaces",
  },
  {
    id: "5",
    name: "Stacking Rings 5 Pack",
    iamge: "../asset/img/new-5.jpg",
    price: 38.24,
    hot: "HOT",
    category: "rings",
  },
  {
    id: "6",
    name: "Gold Vermeil Chunky Bracelet",
    iamge: "../asset/img/new-6.jpg",
    price: 69.2,

    hot: "HOT",
    category: "bracelets",
  },
  {
    id: " 7",
    name: "Baguette Rings Set of Two Blue",
    iamge: "../asset/img/new-7.jpg",
    price: 38.24,
    hot: "HOT",
    category: "rings",
  },
  {
    id: "8",
    name: "London Charm Bracelet",
    iamge: "../asset/img/new-8.jpg",
    price: 168.99,

    hot: "HOT",
    category: "bracelets",
  },
  {
    id: "9",
    name: "Retreat Twisted Loop Earring",
    iamge: "../asset/img/shop-1.jpg",
    price: 31.76,
    hot: "HOT",
    category: "Earrings",
  },
  {
    id: "10",
    name: "Stone Short Drop Earrings",
    iamge: "../asset/img/shop-2.jpg",
    price: 149.99,
    hot: "HOT",
    category: "Earrings",
  },
  {
    id: "11",
    name: "Beaded Hoop Earrings ",
    iamge: "../asset/img/shop-3.jpg",
    price: 59.99,
    hot: "-14%",
    category: "Earrings",
  },
  {
    id: " 12",
    name: "Linked Circle Short Drop Earrings",
    iamge: "../asset/img/shop-4.jpg",
    price: 38.99,
    hot: "7%",
    category: "Earrings",
  },
  {
    id: " 13",
    name: "Leaf Short Drop Earrings",
    iamge: "../asset/img/shop-5.jpg",
    price: 38.99,
    hot: "Hot",
    category: "Earrings",
  },
  {
    id: " 14",
    name: "Gold-plated Pearl Necklace",
    iamge: "../asset/img/shop-6.jpg",
    price: 89.99,
    hot: "-41%",
    category: "necklaces",
  },
  {
    id: " 15",
    name: "Necklaces and Pendants for Women",
    iamge: "../asset/img/shop-7.jpg",
    price: 100.99,
    hot: "Hot",
    category: "necklaces",
  },
  {
    id: " 16",
    name: "Cream Suedette Panel Cross Body Bag",
    iamge: "../asset/img/shop-8.jpg",
    price: 450.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "17",
    name: "Pale Yellow Quilted Chain Cross Body Bag",
    iamge: "../asset/img/shop-9.jpg",
    price: 350.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "18",
    name: "Cream Quilted Twist Lock Cross Body Bag",
    iamge: "../asset/img/shop-10.jpg",
    price: 142.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: " 19",
    name: "Embroidered Camera Bag",
    iamge: "../asset/img/shop-11.jpg",
    price: 42.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "20",
    name: "Leather-Look Embossed Cross Body Bag",
    iamge: "../asset/img/shop-12.jpg",
    price: 122.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "21",
    name: "Loop Buckle Saddle Bag",
    iamge: "../asset/img/shop-13.jpg",
    price: 130.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: " 22",
    name: "Off White Faux Croc Cross Body Bag",
    iamge: "../asset/img/shop-14.jpg",
    price: 340.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "23",
    name: "Brown Leopard Print Weekend Bag",
    iamge: "../asset/img/shop-15.jpg",
    price: 640.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: " 24",
    name: "Pale Pink Quilted Chain Cross Body Bag",
    iamge: "../asset/img/shop-16.jpg",
    price: 560.94,
    hot: "Hot",
    category: "bags",
  },
  {
    id: "25",
    name: "Topshop Retro Style Sunglasses",
    iamge: "../asset/img/shop-17.jpg",
    price: 89.74,
    hot: "Hot",
    category: "glasses",
  },
  {
    id: "26",
    name: "Polarized Clip-On Sunglasses",
    iamge: "../asset/img/shop-18.jpg",

    price: 49.74,
    hot: "-29%",
    category: "glasses",
  },
  {
    id: " 27",
    name: "Belgium Photochromic Sunglasses",
    iamge: "../asset/img/shop-19.jpg",
    price: 40.38,
    hot: "Hot",
    category: "glasses",
  },
  {
    id: " 28",
    name: "Sinner Rockford Sunglasses",
    iamge: "../asset/img/shop-20.jpg",

    price: 199.99,
    hot: "-50%",
    category: "glasses",
  },
  {
    id: "29",
    name: "Ring Foresh Feather",
    iamge: "../asset/img/shop-21.jpg",
    price: 14.55,
    hot: "HOT",
    category: "rings",
  },
  {
    id: "30",
    name: "Napkin Ring Metal Leaf",
    iamge: "../asset/img/shop-22.jpg",
    price: "$147.55",
    hot: "-40%",
    category: "rings",
  },
];
export default shopitems;
